# API Keys
[env]
RAPIDAPI_KEY = "cdee5e97c8msh34c3fd1e0516cb2p13b5bdjsn85e981b0d4a5"
GEMINI_API_KEY = "AIzaSyDMSymgYl_BNzq7h-agexQ9MchDJGcYSkw"
GOOGLE_API_KEY = "AIzaSyDMSymgYl_BNzq7h-agexQ9MchDJGcYSkw"
OPENAI_API_KEY = "your-openai-key-here" 