# API Keys
[env]
RAPIDAPI_KEY = "a5c0896b36mshaa509a779a23bb6p181f51jsna75ba55edc97"
GEMINI_API_KEY = "AIzaSyDMSymgYl_BNzq7h-agexQ9MchDJGcYSkw"
GOOGLE_API_KEY = "AIzaSyDMSymgYl_BNzq7h-agexQ9MchDJGcYSkw"
OPENAI_API_KEY = "your-openai-key-here" 